const GET_MOVIES = 'GET_MOVIES'
const GET_MORE_MOVIES = 'GET_MORE_MOVIES'
const GET_GENRES = 'GET_GENRES'
const CHANGE_THEME = 'CHANGE_THEME'

export {GET_MOVIES, GET_MORE_MOVIES, GET_GENRES, CHANGE_THEME}