const GET_MOVIES_LIST = 'GET_MOVIES_LIST'
const GET_NEXT_MOVIES_LIST_PAGE = 'GET_NEXT_MOVIES_LIST_PAGE'
const GET_GENRES = 'GET_GENRES'
const CHANGE_THEME = 'CHANGE_THEME'
const GET_TOP_RATED_MOVIES = 'GET_TOP_RATED_MOVIES'
const GET_UPCOMING_MOVIES = 'GET_UPCOMING_MOVIES'

export {GET_MOVIES_LIST, GET_NEXT_MOVIES_LIST_PAGE, GET_GENRES, CHANGE_THEME, GET_TOP_RATED_MOVIES, GET_UPCOMING_MOVIES}